# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcus/buildfpmc2/fpmc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcus/makefpmc5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcus/makefpmc5/CMakeFiles /home/marcus/makefpmc5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcus/makefpmc5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fpmc-lhe

# Build rule for target.
fpmc-lhe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpmc-lhe
.PHONY : fpmc-lhe

# fast build rule for target.
fpmc-lhe/fast:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/build
.PHONY : fpmc-lhe/fast

#=============================================================================
# Target rules for targets named Fpmc

# Build rule for target.
Fpmc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Fpmc
.PHONY : Fpmc

# fast build rule for target.
Fpmc/fast:
	$(MAKE) -f CMakeFiles/Fpmc.dir/build.make CMakeFiles/Fpmc.dir/build
.PHONY : Fpmc/fast

#=============================================================================
# Target rules for targets named fpmc

# Build rule for target.
fpmc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpmc
.PHONY : fpmc

# fast build rule for target.
fpmc/fast:
	$(MAKE) -f CMakeFiles/fpmc.dir/build.make CMakeFiles/fpmc.dir/build
.PHONY : fpmc/fast

#=============================================================================
# Target rules for targets named fpmc-hepmc

# Build rule for target.
fpmc-hepmc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpmc-hepmc
.PHONY : fpmc-hepmc

# fast build rule for target.
fpmc-hepmc/fast:
	$(MAKE) -f CMakeFiles/fpmc-hepmc.dir/build.make CMakeFiles/fpmc-hepmc.dir/build
.PHONY : fpmc-hepmc/fast

#=============================================================================
# Target rules for targets named FPMCCore

# Build rule for target.
FPMCCore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FPMCCore
.PHONY : FPMCCore

# fast build rule for target.
FPMCCore/fast:
	$(MAKE) -f Fpmc/CMakeFiles/FPMCCore.dir/build.make Fpmc/CMakeFiles/FPMCCore.dir/build
.PHONY : FPMCCore/fast

#=============================================================================
# Target rules for targets named miscellaneous

# Build rule for target.
miscellaneous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 miscellaneous
.PHONY : miscellaneous

# fast build rule for target.
miscellaneous/fast:
	$(MAKE) -f Fpmc/External/CMakeFiles/miscellaneous.dir/build.make Fpmc/External/CMakeFiles/miscellaneous.dir/build
.PHONY : miscellaneous/fast

#=============================================================================
# Target rules for targets named CHIDe

# Build rule for target.
CHIDe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CHIDe
.PHONY : CHIDe

# fast build rule for target.
CHIDe/fast:
	$(MAKE) -f Fpmc/External/CHIDe/CMakeFiles/CHIDe.dir/build.make Fpmc/External/CHIDe/CMakeFiles/CHIDe.dir/build
.PHONY : CHIDe/fast

#=============================================================================
# Target rules for targets named KMR_lumi

# Build rule for target.
KMR_lumi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KMR_lumi
.PHONY : KMR_lumi

# fast build rule for target.
KMR_lumi/fast:
	$(MAKE) -f Fpmc/External/kmrlumi/CMakeFiles/KMR_lumi.dir/build.make Fpmc/External/kmrlumi/CMakeFiles/KMR_lumi.dir/build
.PHONY : KMR_lumi/fast

#=============================================================================
# Target rules for targets named KMR_lumi_2

# Build rule for target.
KMR_lumi_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KMR_lumi_2
.PHONY : KMR_lumi_2

# fast build rule for target.
KMR_lumi_2/fast:
	$(MAKE) -f Fpmc/External/kmrlumi2/CMakeFiles/KMR_lumi_2.dir/build.make Fpmc/External/kmrlumi2/CMakeFiles/KMR_lumi_2.dir/build
.PHONY : KMR_lumi_2/fast

#=============================================================================
# Target rules for targets named excl_aaaa

# Build rule for target.
excl_aaaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 excl_aaaa
.PHONY : excl_aaaa

# fast build rule for target.
excl_aaaa/fast:
	$(MAKE) -f Fpmc/External/excl_aaaa/CMakeFiles/excl_aaaa.dir/build.make Fpmc/External/excl_aaaa/CMakeFiles/excl_aaaa.dir/build
.PHONY : excl_aaaa/fast

#=============================================================================
# Target rules for targets named comphep

# Build rule for target.
comphep: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comphep
.PHONY : comphep

# fast build rule for target.
comphep/fast:
	$(MAKE) -f Fpmc/External/comphep_interface/CMakeFiles/comphep.dir/build.make Fpmc/External/comphep_interface/CMakeFiles/comphep.dir/build
.PHONY : comphep/fast

#=============================================================================
# Target rules for targets named sqme_aaaa

# Build rule for target.
sqme_aaaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqme_aaaa
.PHONY : sqme_aaaa

# fast build rule for target.
sqme_aaaa/fast:
	$(MAKE) -f Fpmc/External/comphep_interface/sqme_aaaa/CMakeFiles/sqme_aaaa.dir/build.make Fpmc/External/comphep_interface/sqme_aaaa/CMakeFiles/sqme_aaaa.dir/build
.PHONY : sqme_aaaa/fast

#=============================================================================
# Target rules for targets named sqme_aazz

# Build rule for target.
sqme_aazz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqme_aazz
.PHONY : sqme_aazz

# fast build rule for target.
sqme_aazz/fast:
	$(MAKE) -f Fpmc/External/comphep_interface/sqme_aazz/CMakeFiles/sqme_aazz.dir/build.make Fpmc/External/comphep_interface/sqme_aazz/CMakeFiles/sqme_aazz.dir/build
.PHONY : sqme_aazz/fast

#=============================================================================
# Target rules for targets named sqme_aaww

# Build rule for target.
sqme_aaww: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqme_aaww
.PHONY : sqme_aaww

# fast build rule for target.
sqme_aaww/fast:
	$(MAKE) -f Fpmc/External/comphep_interface/sqme_aaww/CMakeFiles/sqme_aaww.dir/build.make Fpmc/External/comphep_interface/sqme_aaww/CMakeFiles/sqme_aaww.dir/build
.PHONY : sqme_aaww/fast

#=============================================================================
# Target rules for targets named softc

# Build rule for target.
softc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 softc
.PHONY : softc

# fast build rule for target.
softc/fast:
	$(MAKE) -f Fpmc/External/softc/CMakeFiles/softc.dir/build.make Fpmc/External/softc/CMakeFiles/softc.dir/build
.PHONY : softc/fast

#=============================================================================
# Target rules for targets named HerwigCore

# Build rule for target.
HerwigCore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HerwigCore
.PHONY : HerwigCore

# fast build rule for target.
HerwigCore/fast:
	$(MAKE) -f Herwig/CMakeFiles/HerwigCore.dir/build.make Herwig/CMakeFiles/HerwigCore.dir/build
.PHONY : HerwigCore/fast

Examples/dummy_hwaend.o: Examples/dummy_hwaend.f.o

.PHONY : Examples/dummy_hwaend.o

# target to build an object file
Examples/dummy_hwaend.f.o:
	$(MAKE) -f CMakeFiles/fpmc.dir/build.make CMakeFiles/fpmc.dir/Examples/dummy_hwaend.f.o
	$(MAKE) -f CMakeFiles/fpmc-hepmc.dir/build.make CMakeFiles/fpmc-hepmc.dir/Examples/dummy_hwaend.f.o
.PHONY : Examples/dummy_hwaend.f.o

Examples/dummy_hwaend.i: Examples/dummy_hwaend.f.i

.PHONY : Examples/dummy_hwaend.i

# target to preprocess a source file
Examples/dummy_hwaend.f.i:
	$(MAKE) -f CMakeFiles/fpmc.dir/build.make CMakeFiles/fpmc.dir/Examples/dummy_hwaend.f.i
	$(MAKE) -f CMakeFiles/fpmc-hepmc.dir/build.make CMakeFiles/fpmc-hepmc.dir/Examples/dummy_hwaend.f.i
.PHONY : Examples/dummy_hwaend.f.i

Examples/dummy_hwaend.s: Examples/dummy_hwaend.f.s

.PHONY : Examples/dummy_hwaend.s

# target to generate assembly for a file
Examples/dummy_hwaend.f.s:
	$(MAKE) -f CMakeFiles/fpmc.dir/build.make CMakeFiles/fpmc.dir/Examples/dummy_hwaend.f.s
	$(MAKE) -f CMakeFiles/fpmc-hepmc.dir/build.make CMakeFiles/fpmc-hepmc.dir/Examples/dummy_hwaend.f.s
.PHONY : Examples/dummy_hwaend.f.s

Examples/fpmc_bare.o: Examples/fpmc_bare.cc.o

.PHONY : Examples/fpmc_bare.o

# target to build an object file
Examples/fpmc_bare.cc.o:
	$(MAKE) -f CMakeFiles/fpmc.dir/build.make CMakeFiles/fpmc.dir/Examples/fpmc_bare.cc.o
.PHONY : Examples/fpmc_bare.cc.o

Examples/fpmc_bare.i: Examples/fpmc_bare.cc.i

.PHONY : Examples/fpmc_bare.i

# target to preprocess a source file
Examples/fpmc_bare.cc.i:
	$(MAKE) -f CMakeFiles/fpmc.dir/build.make CMakeFiles/fpmc.dir/Examples/fpmc_bare.cc.i
.PHONY : Examples/fpmc_bare.cc.i

Examples/fpmc_bare.s: Examples/fpmc_bare.cc.s

.PHONY : Examples/fpmc_bare.s

# target to generate assembly for a file
Examples/fpmc_bare.cc.s:
	$(MAKE) -f CMakeFiles/fpmc.dir/build.make CMakeFiles/fpmc.dir/Examples/fpmc_bare.cc.s
.PHONY : Examples/fpmc_bare.cc.s

Examples/fpmc_hepmc.o: Examples/fpmc_hepmc.cc.o

.PHONY : Examples/fpmc_hepmc.o

# target to build an object file
Examples/fpmc_hepmc.cc.o:
	$(MAKE) -f CMakeFiles/fpmc-hepmc.dir/build.make CMakeFiles/fpmc-hepmc.dir/Examples/fpmc_hepmc.cc.o
.PHONY : Examples/fpmc_hepmc.cc.o

Examples/fpmc_hepmc.i: Examples/fpmc_hepmc.cc.i

.PHONY : Examples/fpmc_hepmc.i

# target to preprocess a source file
Examples/fpmc_hepmc.cc.i:
	$(MAKE) -f CMakeFiles/fpmc-hepmc.dir/build.make CMakeFiles/fpmc-hepmc.dir/Examples/fpmc_hepmc.cc.i
.PHONY : Examples/fpmc_hepmc.cc.i

Examples/fpmc_hepmc.s: Examples/fpmc_hepmc.cc.s

.PHONY : Examples/fpmc_hepmc.s

# target to generate assembly for a file
Examples/fpmc_hepmc.cc.s:
	$(MAKE) -f CMakeFiles/fpmc-hepmc.dir/build.make CMakeFiles/fpmc-hepmc.dir/Examples/fpmc_hepmc.cc.s
.PHONY : Examples/fpmc_hepmc.cc.s

Examples/fpmc_legacy_ffcard.o: Examples/fpmc_legacy_ffcard.cc.o

.PHONY : Examples/fpmc_legacy_ffcard.o

# target to build an object file
Examples/fpmc_legacy_ffcard.cc.o:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_legacy_ffcard.cc.o
.PHONY : Examples/fpmc_legacy_ffcard.cc.o

Examples/fpmc_legacy_ffcard.i: Examples/fpmc_legacy_ffcard.cc.i

.PHONY : Examples/fpmc_legacy_ffcard.i

# target to preprocess a source file
Examples/fpmc_legacy_ffcard.cc.i:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_legacy_ffcard.cc.i
.PHONY : Examples/fpmc_legacy_ffcard.cc.i

Examples/fpmc_legacy_ffcard.s: Examples/fpmc_legacy_ffcard.cc.s

.PHONY : Examples/fpmc_legacy_ffcard.s

# target to generate assembly for a file
Examples/fpmc_legacy_ffcard.cc.s:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_legacy_ffcard.cc.s
.PHONY : Examples/fpmc_legacy_ffcard.cc.s

Examples/fpmc_lhe.o: Examples/fpmc_lhe.f.o

.PHONY : Examples/fpmc_lhe.o

# target to build an object file
Examples/fpmc_lhe.f.o:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_lhe.f.o
.PHONY : Examples/fpmc_lhe.f.o

Examples/fpmc_lhe.i: Examples/fpmc_lhe.f.i

.PHONY : Examples/fpmc_lhe.i

# target to preprocess a source file
Examples/fpmc_lhe.f.i:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_lhe.f.i
.PHONY : Examples/fpmc_lhe.f.i

Examples/fpmc_lhe.s: Examples/fpmc_lhe.f.s

.PHONY : Examples/fpmc_lhe.s

# target to generate assembly for a file
Examples/fpmc_lhe.f.s:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_lhe.f.s
.PHONY : Examples/fpmc_lhe.f.s

Examples/fpmc_load_params.o: Examples/fpmc_load_params.f.o

.PHONY : Examples/fpmc_load_params.o

# target to build an object file
Examples/fpmc_load_params.f.o:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_load_params.f.o
.PHONY : Examples/fpmc_load_params.f.o

Examples/fpmc_load_params.i: Examples/fpmc_load_params.f.i

.PHONY : Examples/fpmc_load_params.i

# target to preprocess a source file
Examples/fpmc_load_params.f.i:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_load_params.f.i
.PHONY : Examples/fpmc_load_params.f.i

Examples/fpmc_load_params.s: Examples/fpmc_load_params.f.s

.PHONY : Examples/fpmc_load_params.s

# target to generate assembly for a file
Examples/fpmc_load_params.f.s:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_load_params.f.s
.PHONY : Examples/fpmc_load_params.f.s

Examples/fpmc_main_lhe.o: Examples/fpmc_main_lhe.f.o

.PHONY : Examples/fpmc_main_lhe.o

# target to build an object file
Examples/fpmc_main_lhe.f.o:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_main_lhe.f.o
.PHONY : Examples/fpmc_main_lhe.f.o

Examples/fpmc_main_lhe.i: Examples/fpmc_main_lhe.f.i

.PHONY : Examples/fpmc_main_lhe.i

# target to preprocess a source file
Examples/fpmc_main_lhe.f.i:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_main_lhe.f.i
.PHONY : Examples/fpmc_main_lhe.f.i

Examples/fpmc_main_lhe.s: Examples/fpmc_main_lhe.f.s

.PHONY : Examples/fpmc_main_lhe.s

# target to generate assembly for a file
Examples/fpmc_main_lhe.f.s:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_main_lhe.f.s
.PHONY : Examples/fpmc_main_lhe.f.s

Examples/fpmc_var_ini.o: Examples/fpmc_var_ini.f.o

.PHONY : Examples/fpmc_var_ini.o

# target to build an object file
Examples/fpmc_var_ini.f.o:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_var_ini.f.o
.PHONY : Examples/fpmc_var_ini.f.o

Examples/fpmc_var_ini.i: Examples/fpmc_var_ini.f.i

.PHONY : Examples/fpmc_var_ini.i

# target to preprocess a source file
Examples/fpmc_var_ini.f.i:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_var_ini.f.i
.PHONY : Examples/fpmc_var_ini.f.i

Examples/fpmc_var_ini.s: Examples/fpmc_var_ini.f.s

.PHONY : Examples/fpmc_var_ini.s

# target to generate assembly for a file
Examples/fpmc_var_ini.f.s:
	$(MAKE) -f CMakeFiles/fpmc-lhe.dir/build.make CMakeFiles/fpmc-lhe.dir/Examples/fpmc_var_ini.f.s
.PHONY : Examples/fpmc_var_ini.f.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... fpmc-lhe"
	@echo "... Fpmc"
	@echo "... edit_cache"
	@echo "... fpmc"
	@echo "... rebuild_cache"
	@echo "... fpmc-hepmc"
	@echo "... FPMCCore"
	@echo "... miscellaneous"
	@echo "... CHIDe"
	@echo "... KMR_lumi"
	@echo "... KMR_lumi_2"
	@echo "... excl_aaaa"
	@echo "... comphep"
	@echo "... sqme_aaaa"
	@echo "... sqme_aazz"
	@echo "... sqme_aaww"
	@echo "... softc"
	@echo "... HerwigCore"
	@echo "... Examples/dummy_hwaend.o"
	@echo "... Examples/dummy_hwaend.i"
	@echo "... Examples/dummy_hwaend.s"
	@echo "... Examples/fpmc_bare.o"
	@echo "... Examples/fpmc_bare.i"
	@echo "... Examples/fpmc_bare.s"
	@echo "... Examples/fpmc_hepmc.o"
	@echo "... Examples/fpmc_hepmc.i"
	@echo "... Examples/fpmc_hepmc.s"
	@echo "... Examples/fpmc_legacy_ffcard.o"
	@echo "... Examples/fpmc_legacy_ffcard.i"
	@echo "... Examples/fpmc_legacy_ffcard.s"
	@echo "... Examples/fpmc_lhe.o"
	@echo "... Examples/fpmc_lhe.i"
	@echo "... Examples/fpmc_lhe.s"
	@echo "... Examples/fpmc_load_params.o"
	@echo "... Examples/fpmc_load_params.i"
	@echo "... Examples/fpmc_load_params.s"
	@echo "... Examples/fpmc_main_lhe.o"
	@echo "... Examples/fpmc_main_lhe.i"
	@echo "... Examples/fpmc_main_lhe.s"
	@echo "... Examples/fpmc_var_ini.o"
	@echo "... Examples/fpmc_var_ini.i"
	@echo "... Examples/fpmc_var_ini.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

